"""empty message

Revision ID: 3bc326ca923d
Revises: 1d67d1756aa2
Create Date: 2025-09-09 16:00:35.647780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc326ca923d'
down_revision: Union[str, Sequence[str], None] = '1d67d1756aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_groups_join_token'), 'groups', ['join_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_join_token'), table_name='groups')
    # ### end Alembic commands ###
