"""empty message

Revision ID: 6f20572ebd5a
Revises: 3bc326ca923d
Create Date: 2025-09-09 16:15:23.767245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f20572ebd5a'
down_revision: Union[str, Sequence[str], None] = '3bc326ca923d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_owner_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('groups_group_owner_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['group_owner_id'], ['id'])
    op.drop_column('groups', 'group_owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_group_owner_fkey'), 'groups', 'users', ['group_owner'], ['id'])
    op.drop_column('groups', 'group_owner_id')
    # ### end Alembic commands ###
