"""empty message

Revision ID: fc41a83e817c
Revises: 9cca4467a226
Create Date: 2025-09-09 15:09:19.388482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc41a83e817c'
down_revision: Union[str, Sequence[str], None] = '9cca4467a226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'users', ['group_owner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'group_owner')
    # ### end Alembic commands ###
