"""empty message

Revision ID: 976cf9c31b5e
Revises: 01f3c71b37cc
Create Date: 2025-09-10 18:36:53.206467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976cf9c31b5e'
down_revision: Union[str, Sequence[str], None] = '01f3c71b37cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('groups_name_key'), 'groups', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('groups_name_key'), 'groups', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
